language: go
go:
    - 1.3

notifications:
    email: true

addons:
    postgresql: "9.3"

before_script:
  - psql --file=ps2_db.sql -U postgres

script:
  - export POSTGRESQL_USER="postgres"
  - export POSTGRESQL_PASS=""
  - export PGHOST="localhost"
  - go test -v ./...

install:
  - go get -v github.com/stretchr/testify/assert
  - go get -v github.com/lib/pq
  - go get -d -t -v ./...
  - go build -v -i ./...
