language: go
go:
    - 1.3

notifications:
    email: true

addons:
    postgresql: "9.3"

before_script:
  - psql --file=ps2_db.sql -U postgres

script: bash install.sh

install:
  - go get github.com/stretchr/testify/assert
  - go get github.com/lib/pq
